#!/bin/sh

# A pre-push hook
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#

remote="$1"
url="$2"

echo ${PWD}
ls

# Update data files
cp task-cpu/vanessa-thinkpad-t460s_vanessa.json data/task-cpu.json
cp task-system/vanessa-thinkpad-t460s_vanessa.json data/task-system.json
cp task-sensors/vanessa-thinkpad-t460s_vanessa.json data/task-sensors.json
cp task-memory/vanessa-thinkpad-t460s_vanessa.json data/task-memory.json

# If the container to do the work doesn't exist, pull it
if [ ! -f "data/python-datascience.sif" ];
    then
    singularity pull --name data/python-datascience.sif docker://faizanbashir/python-datascience:3.6
fi

# Then run the generate.py script
singularity exec data/python-datascience.sif python3 data/generate.py

# Make the output folder
mkdir -p docs
cp -R data/img/*.png docs/

# Get Listing of files
FILES=$(ls docs/*.png)

# Generate a README with images
echo "# WatchMe System Images" > docs/README.md

for FILE in ${FILES}; do
    if [ ! -f "${FILE}" ]; then
        echo "Cannot find ${FILE}";
        exit 1;
    else
        FILENAME=$(basename $FILE)
        echo "![${FILENAME}](${FILENAME})\n" >> docs/README.md
    fi
done

git add docs/*
git commit -a -m 'adding rendering of system images to docs folder'

exit 0
